### ISSUE TITLE
Can't get velocity out of fuzzylite

### ISSUE THREAD

**Issue by maxlein** [gKouros/rsband_local_planner#10] opened 2018-01-05 14:08 UTC
Hi, 

I am experimenting with your controller but I don't get any velocities out of it.
See here an output:

`Ea: 23.224841, Eo: 28.349788, Ep: 5.055443, Ey: 1.993565
[ INFO] [1515160524.377827833, 8.000000000]: vel: 0.000, front steering angle: 14.324, ready: 1, status: `

I didn't change any of your fuzzy rules, all default.
Steering angle looks plausible, but I don't know what I am missing.

**Comment by maxlein** [comment] 2018-01-07 20:20
You have a nasty bug here:
`if (pnh_->getParam("fuzzy_rules/rear_steering_deviation_rules",
          speedRules_))
        ROS_WARN("Failed to load rear steering deviation fuzzy rules!");`

**Comment by gkouros** [comment] 2018-01-08 08:03
Hi maxlein,

Thank you for pointing out the bug. I already pushed a fix.
Do you still get zero velocity after the fix?

In case, the issue persists, please specify the ros
distribution you use so that I can investigate the cause.

**Comment by maxlein** [comment] 2018-01-09 20:04
No thanks, this fixed it.
But a bit more documentstion would be nice as your planner seems to be one of a few if not the only planner that really works with a car. Although car abilities like turning radius are not taken into account by the planner, only after the controller's output.

**Closed as completed** 2018-03-17 12:28 UTC
